name: Comment

on:
  pull_request:
    types: [opened, edited, reopened, labeled]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Nice PR!

